### ISSUE TITLE
Commenting doesnt work

### ISSUE THREAD

**Issue by hex007** [ShaneWilton/sublime-smali#4]
The comment code doesnt work

**Comment by CalebFenton** [comment]
Could you post some example code?

**Comment by hex007** [comment]
Sample code :

//# direct methods
.method private constructor <init>()V
    .locals 0
    .parameter "test"

    .prologue
    .line 20
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Try ctrl+/ which is sublime default for comment on any line or selection.

Expected O/P selection or line toggles as comment

Currently nothing happens. I have written a macro to do that. Commenting works nicely.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[
	{
		"args":
		{
			"extend": true,
			"to": "eol"
		},
		"command": "move_to"
	},
	{
		"args": null,
		"command": "split_selection_into_lines"
	},
	{
		"args":
		{
			"extend": false,
			"to": "bol"
		},
		"command": "move_to"
	},
	{
		"args":
		{
			"extend": false,
			"to": "bol"
		},
		"command": "move_to"
	},
	{
		"args":
		{
			"characters": "#"
		},
		"command": "insert"
	},
	{
		"args": null,
		"command": "single_selection"
	}
]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Copy+paste this code in new file your_name.sublime-macro in packages dir

The below code is for key binding the code
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[
	// { "keys": ["KEY_COMBO"], "command": "run_macro_file", "args": {"file": "res://Packages/User/FILE_NAME.sublime-macro"} },
	{"keys": ["ctrl+`"], "command": "run_macro_file", "args": {"file": "res://Packages/User/comment_smali.sublime-macro"} }
]

**Comment by CalebFenton** [comment]
Very interesting. So is it the syntax definition that declares what a
comment looks like? That's what it sounds like.


Caleb Fenton

**Comment by hex007** [comment]
Actually # in smali is equivalent to // in java. There isnt any block commenting in smali like /* ~~~ */ in java. All data after a comment  tag is ignored.

**Comment by hex007** [comment]
Any update on this?

**Comment by CalebFenton** [comment]
From what I understand reading about toggle comment functionality for sublime, it is not defined in the syntax definition. It seems like there might be a clean way to bundle it into this plugin, but I need to investigate more.

FYI: This is where I was reading: https://stackoverflow.com/questions/11267389/fix-toggle-comment-functionality-for-batch-files-in-sublime-text
