### ISSUE TITLE
.parameter and .local detected as errors

### ISSUE THREAD

**Issue by hex007** [ShaneWilton/sublime-smali#5]
Initial version had support for this and local and parameter directives weren't  detected as errors

**Comment by CalebFenton** [comment]
Could you post some example code? Parameter is dexlib1 syntax, but locals does work.

**Comment by hex007** [comment]
.method private constructor <init>()V
    .locals 0
    .parameter "test"

    .prologue
    .line 20
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

Previous code

![image](https://cloud.githubusercontent.com/assets/1689246/5979229/df2b25de-a8cb-11e4-94af-228cfe72dcba.png)

Latest code

![image](https://cloud.githubusercontent.com/assets/1689246/5979253/10a4f09a-a8cc-11e4-957f-155f080dc40b.png)

If you want i can post the older code i have

**Comment by CalebFenton** [comment]
Ah, ok so it's just the parameter directive that's being considered an
error. I didn't consider that people would be using the outdated dexlib1,
but it shouldn't be hard to add back in. This can be fixed. The confusing
part was saying locals was broken.

Thanks!

Caleb Fenton

**Comment by hex007** [comment]
I think if proguard is not used, .local and .parameter directives are not removed.

**Comment by hex007** [comment]
Any update on this?

**Comment by CalebFenton** [comment]
The .parameter and the way that .local looks means it's Smali 1.x format. I don't feel like it's worth it to maintain accuracy with a deprecated format. Fixes are forthcoming to properly support Smali 2.x format.
