### ISSUE TITLE
Converted for Atom

### ISSUE THREAD

**Issue by xingrz** [ShaneWilton/sublime-smali#6]
Hi,

I've converted this package for the [Atom](http://atom.io) editor: [xingrz/language-smali](https://github.com/xingrz/language-smali).

Thank you for this package :)

**Comment by CalebFenton** [comment]
Nice! Thanks. I'll spread the word to people I know who use atom.

**Comment by ShaneWilton** [comment]
This is awesome! Thanks @xingrz :D
