### ISSUE TITLE
Can't recognize .param commands and some smalis will treat .field as error

### ISSUE THREAD

**Issue by md500** [ShaneWilton/sublime-smali#7]
cant recognize **.param** commands lines following *p1* to *p6*.(and more pn as possible)

code:

	.method private static getCalculatedRect(Landroid/content/Context;IIILandroid/graphics/Point;ZZ)Landroid/graphics/RectF;
		.locals 14

->>>fix

		.param p0, "context"    # Landroid/content/Context;
		.param p1, "width"    # I
		.param p2, "height"    # I
		.param p3, "quotient"    # I
		.param p4, "point"    # Landroid/graphics/Point;
		.param p5, "isCenterPoint"    # Z
		.param p6, "isSmall"    # Z

<<<-fix

		.prologue
		.line 360
		new-instance v5, Lcom/samsung/android/snote/control/core/note/Note;

		invoke-direct {v5}, Lcom/samsung/android/snote/control/core/note/Note;-><init>()V

		.line 361
		.local v5, "note":Lcom/samsung/android/snote/control/core/note/Note;
		invoke-virtual {v5}, Lcom/samsung/android/snote/control/core/note/Note;->getCanvasHelper()Lcom/samsung/android/snote/control/core/note/canvas/CanvasHelper;

		move-result-object v9

		invoke-virtual {v9}, Lcom/samsung/android/snote/control/core/note/canvas/CanvasHelper;->getZoomRatio()F

		move-result v8

		.line 362
		.local v8, "zoomRatio":F
		const/4 v9, 0x0

		cmpg-float v9, v8, v9

		if-gtz v9, :cond_0

		.line 363
		const/high16 v8, 0x3f800000

		.line 366
		:cond_0
		invoke-static {p0}, Lcom/samsung/android/snote/control/core/object/ObjectUtil;->getSizeBaseOnCanvas(Landroid/content/Context;)Landroid/graphics/Point;

		move-result-object v6

		.line 368
		.local v6, "sizeRealCanvas":Landroid/graphics/Point;
		invoke-static {p0}, Lcom/samsung/android/snote/control/core/object/ObjectUtil;->getSizeBaseOnPageDoc(Landroid/content/Context;)Landroid/graphics/Point;

		move-result-object v7

		.line 370
		.local v7, "sizeScreen":Landroid/graphics/Point;
		iget v9, v7, Landroid/graphics/Point;->x:I

		iget v10, v7, Landroid/graphics/Point;->y:I

		if-le v9, v10, :cond_6

		iget v9, v7, Landroid/graphics/Point;->y:I

		div-int v2, v9, p3

		.line 372
		.local v2, "nBoxRadius":I
		:goto_0
		const/4 v9, 0x2

		move/from16 v0, p3

		if-ne v0, v9, :cond_1

		.line 373
		int-to-float v9, v2

		const/high16 v10, 0x41200000

		invoke-static {p0, v10}, Lcom/samsung/android/snote/control/core/object/ObjectUtil;->convertDpToPx(Landroid/content/Context;F)F

		move-result v10

		sub-float/2addr v9, v10

		float-to-int v2, v9

		.line 376
		:cond_1
		int-to-float v9, v2

		mul-float/2addr v9, v8

		float-to-int v2, v9

		.line 378
		const/4 v3, 0x0

		.line 379
		.local v3, "nCenterX":I
		const/4 v4, 0x0

		.line 381
		.local v4, "nCenterY":I
		if-nez p4, :cond_7

		.line 382
		iget v9, v6, Landroid/graphics/Point;->x:I

		div-int/lit8 v3, v9, 0x2

		.line 383
		iget v9, v6, Landroid/graphics/Point;->y:I

		div-int/lit8 v4, v9, 0x2

		.line 389
		:goto_1
		const/4 v1, 0x0

		.line 391
		.local v1, "calcRect":Landroid/graphics/RectF;
		if-nez p5, :cond_9

		if-eqz p4, :cond_9

		.line 392
		move/from16 v0, p2

		if-le p1, v0, :cond_8

		.line 393
		new-instance v1, Landroid/graphics/RectF;

		.end local v1    # "calcRect":Landroid/graphics/RectF;
		move-object/from16 v0, p4

		iget v9, v0, Landroid/graphics/Point;->x:I

		int-to-float v9, v9

		move-object/from16 v0, p4

		iget v10, v0, Landroid/graphics/Point;->y:I

		int-to-float v10, v10

		move-object/from16 v0, p4

		iget v11, v0, Landroid/graphics/Point;->x:I

		mul-int/lit8 v12, v2, 0x2

		add-int/2addr v11, v12

		int-to-float v11, v11

		mul-int v12, v2, p2

		div-int/2addr v12, p1

		mul-int/lit8 v12, v12, 0x2

		add-int/2addr v12, v4

		int-to-float v12, v12

		invoke-direct {v1, v9, v10, v11, v12}, Landroid/graphics/RectF;-><init>(FFFF)V

		.line 409
		.restart local v1    # "calcRect":Landroid/graphics/RectF;
		:goto_2
		invoke-static {}, Lcom/samsung/android/snote/control/ui/note/NoteActivity;->getHelpMode()Z

		move-result v9

		if-eqz v9, :cond_2

		.line 410
		sget v9, Lcom/samsung/android/snote/control/core/common/Common;->SCREEN_HEIGHT:I

		int-to-float v9, v9

		mul-float/2addr v9, v8

		const/high16 v10, 0x40000000

		div-float/2addr v9, v10

		float-to-int v4, v9

		.line 413
		:cond_2
		if-eqz p6, :cond_3

		.line 414
		invoke-virtual {v1}, Landroid/graphics/RectF;->width()F

		move-result v9

		int-to-float v10, p1

		mul-float/2addr v10, v8

		cmpl-float v9, v9, v10

		if-lez v9, :cond_3

		invoke-virtual {v1}, Landroid/graphics/RectF;->height()F

		move-result v9

		move/from16 v0, p2

		int-to-float v10, v0

		mul-float/2addr v10, v8

		cmpl-float v9, v9, v10

		if-lez v9, :cond_3

		.line 415
		div-int/lit8 v9, p1, 0x2

		int-to-float v9, v9

		mul-float/2addr v9, v8

		invoke-static {v9}, Ljava/lang/Math;->round(F)I

		move-result v9

		sub-int v9, v3, v9

		int-to-float v9, v9

		iput v9, v1, Landroid/graphics/RectF;->left:F

		.line 416
		div-int/lit8 v9, p2, 0x2

		int-to-float v9, v9

		mul-float/2addr v9, v8

		invoke-static {v9}, Ljava/lang/Math;->round(F)I

		move-result v9

		sub-int v9, v4, v9

		int-to-float v9, v9

		iput v9, v1, Landroid/graphics/RectF;->top:F

		.line 417
		div-int/lit8 v9, p1, 0x2

		int-to-float v9, v9

		mul-float/2addr v9, v8

		invoke-static {v9}, Ljava/lang/Math;->round(F)I

		move-result v9

		add-int/2addr v9, v3

		int-to-float v9, v9

		iput v9, v1, Landroid/graphics/RectF;->right:F

		.line 418
		div-int/lit8 v9, p2, 0x2

		int-to-float v9, v9

		mul-float/2addr v9, v8

		invoke-static {v9}, Ljava/lang/Math;->round(F)I

		move-result v9

		add-int/2addr v9, v4

		int-to-float v9, v9

		iput v9, v1, Landroid/graphics/RectF;->bottom:F

		.line 423
		:cond_3
		if-nez p4, :cond_5

		.line 425
		iget v9, v1, Landroid/graphics/RectF;->top:F

		const/4 v10, 0x0

		cmpg-float v9, v9, v10

		if-gez v9, :cond_4

		.line 426
		iget v9, v1, Landroid/graphics/RectF;->left:F

		invoke-static {v9}, Ljava/lang/Math;->abs(F)F

		move-result v9

		const/4 v10, 0x0

		invoke-virtual {v1, v9, v10}, Landroid/graphics/RectF;->offsetTo(FF)V

		.line 428
		:cond_4
		iget v9, v1, Landroid/graphics/RectF;->left:F

		const/4 v10, 0x0

		cmpg-float v9, v9, v10

		if-gez v9, :cond_5

		.line 429
		const/4 v9, 0x0

		iget v10, v1, Landroid/graphics/RectF;->top:F

		invoke-static {v10}, Ljava/lang/Math;->abs(F)F

		move-result v10

		invoke-virtual {v1, v9, v10}, Landroid/graphics/RectF;->offsetTo(FF)V

		.line 432
		:cond_5
		return-object v1

		.line 370
		.end local v1    # "calcRect":Landroid/graphics/RectF;
		.end local v2    # "nBoxRadius":I
		.end local v3    # "nCenterX":I
		.end local v4    # "nCenterY":I
		:cond_6
		iget v9, v7, Landroid/graphics/Point;->x:I

		div-int v2, v9, p3

		goto/16 :goto_0

		.line 385
		.restart local v2    # "nBoxRadius":I
		.restart local v3    # "nCenterX":I
		.restart local v4    # "nCenterY":I
		:cond_7
		move-object/from16 v0, p4

		iget v3, v0, Landroid/graphics/Point;->x:I

		.line 386
		move-object/from16 v0, p4

		iget v4, v0, Landroid/graphics/Point;->y:I

		goto/16 :goto_1

		.line 396
		.restart local v1    # "calcRect":Landroid/graphics/RectF;
		:cond_8
		new-instance v1, Landroid/graphics/RectF;

		.end local v1    # "calcRect":Landroid/graphics/RectF;
		move-object/from16 v0, p4

		iget v9, v0, Landroid/graphics/Point;->x:I

		int-to-float v9, v9

		move-object/from16 v0, p4

		iget v10, v0, Landroid/graphics/Point;->y:I

		int-to-float v10, v10

		move-object/from16 v0, p4

		iget v11, v0, Landroid/graphics/Point;->x:I

		mul-int v12, v2, p1

		div-int v12, v12, p2

		mul-int/lit8 v12, v12, 0x2

		add-int/2addr v11, v12

		int-to-float v11, v11

		move-object/from16 v0, p4

		iget v12, v0, Landroid/graphics/Point;->y:I

		mul-int/lit8 v13, v2, 0x2

		add-int/2addr v12, v13

		int-to-float v12, v12

		invoke-direct {v1, v9, v10, v11, v12}, Landroid/graphics/RectF;-><init>(FFFF)V

		.restart local v1    # "calcRect":Landroid/graphics/RectF;
		goto/16 :goto_2

		.line 400
		:cond_9
		move/from16 v0, p2

		if-le p1, v0, :cond_a

		.line 401
		new-instance v1, Landroid/graphics/RectF;

		.end local v1    # "calcRect":Landroid/graphics/RectF;
		sub-int v9, v3, v2

		int-to-float v9, v9

		mul-int v10, v2, p2

		div-int/2addr v10, p1

		sub-int v10, v4, v10

		int-to-float v10, v10

		add-int v11, v3, v2

		int-to-float v11, v11

		mul-int v12, v2, p2

		div-int/2addr v12, p1

		add-int/2addr v12, v4

		int-to-float v12, v12

		invoke-direct {v1, v9, v10, v11, v12}, Landroid/graphics/RectF;-><init>(FFFF)V

		.restart local v1    # "calcRect":Landroid/graphics/RectF;
		goto/16 :goto_2

		.line 404
		:cond_a
		new-instance v1, Landroid/graphics/RectF;

		.end local v1    # "calcRect":Landroid/graphics/RectF;
		mul-int v9, v2, p1

		div-int v9, v9, p2

		sub-int v9, v3, v9

		int-to-float v9, v9

		sub-int v10, v4, v2

		int-to-float v10, v10

		mul-int v11, v2, p1

		div-int v11, v11, p2

		add-int/2addr v11, v3

		int-to-float v11, v11

		add-int v12, v4, v2

		int-to-float v12, v12

		invoke-direct {v1, v9, v10, v11, v12}, Landroid/graphics/RectF;-><init>(FFFF)V

		.restart local v1    # "calcRect":Landroid/graphics/RectF;
		goto/16 :goto_2
	.end method

and some **.field** and **.local** are recognized as errors(pink color,as background)

code:(field)

	.class public Lcom/samsung/android/snote/control/core/object/ObjectUtil;
	.super Ljava/lang/Object;
	.source "ObjectUtil.java"

	# static fields
	.field private static final CLIPART_HEIGHT:I = 0x1fe

	.field private static final CLIPART_WIDTH:I = 0x1fc

	.field private static final COLORS:[I

	.field private static final COLOR_POS:[F

	.field private static final DEFAULT_BORDER_LINE_COLOR:I = -0xfb7301

	.field private static final DEFAULT_BORDER_WIDTH:I = 0x4

	.field public static final EXTERNAL_FONT_SIZE:I = 0x12

	.field public static final EXTERNAL_LANDSCAPE_LINESPACING:I = 0x18

	.field public static final EXTERNAL_PORTRAIT_LINESPACING:I = 0x20

	.field public static final EXTERNAL_TABLET_FONT_SIZE:I = 0xb

	.field public static final EXTERNAL_TABLET_LANDSCPAPE_LINESPACING:I = 0x17

	.field public static final EXTERNAL_TABLET_PORTRAIT_LINESPACING:I = 0x1c

	.field public static final EXTERNAL_TABLET_TOP_MARGIN:I = -0x12

	.field public static final EXTERNAL_TEXT_BOTTOM_MARGIN:I = 0x32

	.field public static final EXTERNAL_TOP_MARGIN:I = -0x5

	.field public static final ExtraKeyShapeType:Ljava/lang/String; = "shapeType"

	.field private static final FILE_SCHEME:Ljava/lang/String; = "file"

	.field private static final FLIP_DIRECTION_HORIZONTAL:I = 0x2

	.field private static final FLIP_DIRECTION_VERTICAL:I = 0x1

	.field private static final FRAME_SIZE:I = 0x46

	.field public static final LANDSCAPE_EXTERNAL_TEXT_BOTTOM:I = 0x3c

	.field public static final LANDSCAPE_EXTERNAL_TEXT_LEFT:I = 0xa

	.field public static final LANDSCAPE_EXTERNAL_TEXT_RIGHT:I = 0x276

	.field public static final LANDSCAPE_EXTERNAL_TEXT_TOP:I = 0x31

	.field public static final MAP_ADDRESS_GET_KEY:Ljava/lang/String; = "map-address"

	.field public static final MAP_DATA_GET_CAPTURE:I = 0x1

	.field public static final MAP_DATA_GET_KEY:Ljava/lang/String; = "map-data-get-type"

	.field public static final MAP_DATA_GET_NONE:I = 0x0

	.field public static final MAP_DATA_GET_TEXT:I = 0x2

	.field private static final MAX_IMAGESIZE:I = 0x2d0

<<-fix

	.field private static final MULTI_INSERT_GAP:F = 50.0f

->>fix

	.field public static final MULTI_INSERT_MAX:I = 0xa

	.field private static final NETWORK_DISCONNECT:I = -0x64

	.field private static final NETWORK_FLIGHT_ON:I = -0xa

	.field private static final NETWORK_MOBILE_DATA_ON:I = 0x2

	.field private static final NETWORK_ROAMING_ON:I = 0x3

	.field private static final NETWORK_WIFI_ON:I = 0x1

	.field private static final PACKAGE_NAME_SNOTE:Ljava/lang/String; = "com.samsung.android.snote"

	.field private static final PALETTE16_FRAME_X:I = 0x230

	.field private static final PALETTE16_FRAME_Y:I = 0x8c

	.field public static final PORTRAIT_EXTERNAL_TEXT_BOTTOM:I = 0x4b

	.field public static final PORTRAIT_EXTERNAL_TEXT_LEFT:I = 0xa

	.field public static final PORTRAIT_EXTERNAL_TEXT_RIGHT:I = 0x160

	.field public static final PORTRAIT_EXTERNAL_TEXT_TOP:I = 0x31

	.field public static final QUOTIENT_VALUE_CHARTBUILDER:I = 0x2

	.field public static final QUOTIENT_VALUE_DEFAULT:I = 0x3

	.field private static final SHAPE_COLOR:[I

	.field public static SHAPE_TYPE_FIGURE:I = 0x0

	.field public static SHAPE_TYPE_LINE:I = 0x0

	.field public static SHAPE_TYPE_NONE:I = 0x0

	.field public static final TABLET_LANDSCAPE_EXTERNAL_TEXT_BOTTOM:I = 0x72

	.field public static final TABLET_LANDSCAPE_EXTERNAL_TEXT_LEFT:I = 0xc

	.field public static final TABLET_LANDSCAPE_EXTERNAL_TEXT_RIGHT:I = 0x4f4

	.field public static final TABLET_LANDSCAPE_EXTERNAL_TEXT_TOP:I = 0x4a

	.field public static final TABLET_PORTRAIT_EXTERNAL_TEXT_BOTTOM:I = 0x72

	.field public static final TABLET_PORTRAIT_EXTERNAL_TEXT_LEFT:I = 0xc

	.field public static final TABLET_PORTRAIT_EXTERNAL_TEXT_RIGHT:I = 0x314

	.field public static final TABLET_PORTRAIT_EXTERNAL_TEXT_TOP:I = 0x4a

	.field private static final TAG:Ljava/lang/String; = "ObjectUtil"

	.field public static final VIDEO_SCREEN_SIZE_DEVISION_VALUE:I = 0x3

and here:(local)

	.method public static getTextBoxDefaultHeight(Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;)I
		.locals 8
		.param p0, "textBox"    # Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;

		.prologue
		.line 322
		if-nez p0, :cond_0

		.line 323
		const/4 v6, 0x0

		.line 350
		:goto_0
		return v6

		.line 325
		:cond_0
		invoke-virtual {p0}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->getTopMargin()F

		move-result v6

		invoke-virtual {p0}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->getBottomMargin()F

		move-result v7

		add-float/2addr v6, v7

		invoke-static {v6}, Ljava/lang/Math;->round(F)I

		move-result v0

		.line 326
		.local v0, "absoluteHeight":I
		const/4 v1, 0x0

		.line 327
		.local v1, "fontSize":F
		invoke-virtual {p0}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->getCursorPos()I

		move-result v6

		invoke-virtual {p0}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->getCursorPos()I

		move-result v7

		invoke-virtual {p0, v6, v7}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->findSpans(II)Ljava/util/ArrayList;

		move-result-object v5

		.line 329

->>>fix

		.local v5, "sInfo":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextSpanInfo;>;"

<<<-fix

		if-eqz v5, :cond_2

		.line 330
		invoke-virtual {v5}, Ljava/util/ArrayList;->iterator()Ljava/util/Iterator;

		move-result-object v2

		.local v2, "i$":Ljava/util/Iterator;
		:cond_1
		invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

		move-result v6

		if-eqz v6, :cond_2

		invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

		move-result-object v3

		check-cast v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextSpanInfo;

		.line 331
		.local v3, "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextSpanInfo;
		instance-of v6, v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$FontSizeSpanInfo;

		if-eqz v6, :cond_1

		.line 332
		check-cast v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$FontSizeSpanInfo;

		.end local v3    # "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextSpanInfo;
		iget v1, v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$FontSizeSpanInfo;->fontSize:F

		.line 338
		.end local v2    # "i$":Ljava/util/Iterator;
		:cond_2
		invoke-virtual {p0}, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox;->getParagraph()Ljava/util/ArrayList;

		move-result-object v4

		.line 339
->>>fix

		.local v4, "pInfo":Ljava/util/ArrayList;, "Ljava/util/ArrayList<Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;>;"

->>>fix

		if-eqz v4, :cond_5

		.line 340
		invoke-virtual {v4}, Ljava/util/ArrayList;->iterator()Ljava/util/Iterator;

		move-result-object v2

		.restart local v2    # "i$":Ljava/util/Iterator;
		:cond_3
		:goto_1
		invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

		move-result v6

		if-eqz v6, :cond_5

		invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

		move-result-object v3

		check-cast v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;

		.line 341
		.local v3, "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;
		instance-of v6, v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;

		if-eqz v6, :cond_3

		move-object v6, v3

		.line 342
		check-cast v6, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;

		iget v6, v6, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;->type:I

		const/4 v7, 0x1

		if-ne v6, v7, :cond_4

		.line 343
		int-to-float v6, v0

		check-cast v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;

		.end local v3    # "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;
		iget v7, v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;->lineSpacing:F

		mul-float/2addr v7, v1

		add-float/2addr v6, v7

		float-to-int v0, v6

		goto :goto_1

		.line 345
		.restart local v3    # "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;
		:cond_4
		int-to-float v6, v0

		check-cast v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;

		.end local v3    # "info":Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$TextParagraphInfo;
		iget v7, v3, Lcom/samsung/android/sdk/pen/document/SpenObjectTextBox$LineSpacingParagraphInfo;->lineSpacing:F

		add-float/2addr v6, v7

		float-to-int v0, v6

		goto :goto_1

		.line 350
		.end local v2    # "i$":Ljava/util/Iterator;
		:cond_5
		int-to-double v6, v0

		invoke-static {v6, v7}, Ljava/lang/Math;->ceil(D)D

		move-result-wide v6

		double-to-int v6, v6

		goto :goto_0
	.end method

This Issue are applicable in Samsung Aplications stuff

**Comment by CalebFenton** [comment]
Fixed with https://github.com/ShaneWilton/sublime-smali/commit/c2110fecd34bf97b5909395c9d1e102a8078543b and https://github.com/ShaneWilton/sublime-smali/commit/42b6e4696a3330e457c469e416b2cb67849dbb79. Could you make sure this covers everything for you?

**Comment by md500** [comment]
Yes! Thanks for the nasty fix! (add it for upgrade for Package Manager due for manual upgrade)

**Comment by CalebFenton** [comment]
Sure. :) Thanks for the good description.

I believe package manager just pulls from the repo, so the update is live.
